name: test-action
on:
  push:
    branches: [ main ] 
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 22f3000730@ds.study.iitm.ac.in
        run: echo "Hello, world!"
